### ISSUE TITLE
Need help with model design problem

### ISSUE THREAD

**Issue by chocstarfish** [strongloop/loopback-example-app#45]
I want to extend the sample app by adding make, series and model information to the car. Their relations should be like following:
One make has many series';
One series has many models;
One car has one model.

I created three additional models: make, series and model, each has their own properties(for instance, name).

The question is how should I set their relations in order to enable functionality that client can query a list of cars with their makes', series' and models' names along with the cars' properties? If that is possible, what would the query url be like?

**Comment by crandmck** [comment]
Please ask for help on specific issues at https://groups.google.com/forum/#!forum/loopbackjs.
