### ISSUE TITLE
where is the "app"?

### ISSUE THREAD

**Issue by uNki23** [strongloop/loopback-example-app#65]
hi!

the description says there is an app with features like authorization. i can't find that stuff in the code? there's just an index.html which has some hard-coded api-links in it. 

did you remove the other parts of the app? this example is actually nothing more than showing how to use filters while working with the rest endpoints?

thank you very much!

**Comment by jakerella** [comment]
LoopBack includes most of these features by default. For example, authentication and authorization are built in with the included `User` and `AccessToken` objects. If you run the application and then navigate to http://localhost:3000/explorer you can see all of the API endpoints, included the `User` object and its `/User/login` endpoint. Of course, you'll need to create a user first with a POST to `/User`.

This example application is only intended to show off the back end, API side of things. If you want to see a "full stack" application with an Angular front end then check out the ["Full Stack"](https://github.com/strongloop/loopback-example-full-stack) example repo.

Closing for now, but feel free to reopen if you have other questions.

**Comment by superkhau** [comment]
@uNki23 See strongloop/loopback-example-access-control

**Comment by uNki23** [comment]
thank you!
