### ISSUE TITLE
Use Case: run a lb from, for example, cron for a one-shot job

### ISSUE THREAD

**Issue by OwenBrotherwood** [strongloop/loopback-example-app#67]
From gitter.im.
I want to "do something" in a cron job with the lb structure, but the job does not stop.

The use of not using app.start
[Take loopback-example-app](http://docs.strongloop.com/display/public/LB/LoopBack+example+app) and [stop the app.start](https://github.com/strongloop/loopback-example-app/blob/master/server/server.js#L41-44).
The result is a script that uses lb structure and exits with "Sample data was imported".

Needs a Dev to say ok and a @crandmck to find an appropriate place for this use case in doc.

Pull Request for change of example to indicate the use of no app.start in the code is possible as well, if deemed appropriate, or part of the "etc" in https://github.com/strongloop/loopback/issues/1352

**Comment by crandmck** [comment]
Is this actionable?  If not, can it be closed?

**Comment by crandmck** [comment]
@OwenBrotherwood I don't think this repo is the best place for an issue of this nature.  If you want to pursue this question, I suggest either asking on the forum https://groups.google.com/forum/#!forum/loopbackjs or perhaps opening an issue against the main loopback repo.

**Comment by OwenBrotherwood** [comment]
:+1: I get back on this as the winter months draw in
