### ISSUE TITLE
Why the new  web page  was unable to show if not restart the project 

### ISSUE THREAD

**Issue by xinshouke** [strongloop/loopback-example-app#71]
I put some html into folder client in strongloop project,  I may get the page in browser thr http. But I update some html, the pages were not refreash until I restart the project. Would you tell me is there another way to refreash the page but not restart the project please?

**Comment by jakerella** [comment]
My guess is that this is simply a caching issue. Have you tried to do a hard refresh (which clears your cache of that URL before requesting the page again)?

If that doesn't work, can you share your code with us? I am able to refresh HTML pages and see changes without restarting.

**Comment by superkhau** [comment]
@xinshouke Try using a live-reload tool to help your development. See https://www.npmjs.com/package/livereload

For future reference, please post questions to https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Reporting-issues#question for more details.
