### ISSUE TITLE
need to update loopback-example-app

### ISSUE THREAD

**Issue by altsang** [strongloop/loopback-example-app#75]
As a SL developer, if I were not scaffolding a LB app using `slc`, I would still want to be able to refer to a LB example app by cloning a repo.

- [ ] update example to LB 2.0
- [ ] include middleware.json
- [x] remove references to StrongOps - remove last two bullet points and add - "Install strongloop - `npm install - g strongloop` - and run `slc arc` to check out the rest of StrongLoop"
- [ ] Make sure scaffolding via `slc loopback:example` clones the latest changes

**Comment by superkhau** [comment]
@chandadharap FYI, @altsang needs this issue bumped up in priority.

**Comment by superkhau** [comment]
@altsang When is the deadline? It's obviously ASAP, but I would like to know what I'm working with.

**Comment by altsang** [comment]
note - please do bullet item 3 first and commit, the middleware.json is less priority, deadline is tomorrow morning?

**Comment by altsang** [comment]
critical path - bullet item 3 - should be quick, I can dance around not having middleware.json

**Comment by superkhau** [comment]
Bullet 4 is the lowest priority as discussed with @altsang over Slack.

**Comment by crandmck** [comment]
Note this is a dup of https://github.com/strongloop/loopback-example-app/issues/73 which Hage and I have been working on for weeks.
It depends on fixing some core issues in LB, namely:
 - https://github.com/strongloop/loopback-boot/issues/75
 - https://github.com/strongloop/loopback-explorer/pull/104

**Comment by bajtos** [comment]
@crandmck has described the current status very well.

There is one thing to add: loopback-explorer will support loading via component-config.json in the new major version 2.0, which is currently waiting for me to finish Swagger upgrade to Swagger Spec 2.0.

**Comment by superkhau** [comment]
Spoke with @altsang and he decided that there wasn't enough time to pursue the rest of the bullet items. Basically, update the text in the "Choose your own adventure" section. Closing, reopen if you guys feel the need to keep this around.
