### ISSUE TITLE
Error in API Explorer

### ISSUE THREAD

**Issue by crandmck** [strongloop/loopback-example-app#78]
When I run the app and go to `http://0.0.0.0:3000/explorer/`, there is an error (lower right):
![lb-example-app error](https://cloud.githubusercontent.com/assets/2925364/9946724/ffc52dac-5d49-11e5-858d-bfe3e401e0f8.png)

Click on it and it goes to URL http://online.swagger.io/validator/debug?url=http://0.0.0.0:3000/explorer/swagger.json you see this:
```
[{"level":"error","message":"Can't read from file http://0.0.0.0:3000/explorer/swagger.json"}]
```
HOWEVER, http://localhost:3000/explorer/ works fine and you see the normal message
> [ base url: /api , api version: 3.2.0 ]

@hacksparrow Can you pls take a look?

@bajtos Raymond said you were aware of this, and that this ver. of lb-explorer generates Swagger 2.0 spec.  How do we fix this?

**Comment by hacksparrow** [comment]
@crandmck yes, we are aware about this. It's being discussed at https://github.com/strongloop/loopback-component-explorer/issues/120.

**Comment by crandmck** [comment]
Duplicate of https://github.com/strongloop/loopback-component-explorer/issues/120
